<a href="https://colab.research.google.com/github/SyedMufassirShah/Advance-Class-Based-Views-and-Styling-via-Bootstrap-Django/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch


In [2]:
# Checking Pytorch Version
torch.__version__

'2.11.0+cu128'

In [3]:
# Differenc between the torch.tensor() & torch.Tensor()

#  The torch.tensor(7) will create a tensor with 7 as an item and will have 0-dimmention
scalar = torch.tensor(7)
scalar
# While the torch.Tensor(7) will create 7 index places with random values and will have the shape of (1,7)
scalar2 = torch.Tensor(7)
scalar2

tensor([4.2796e-17, 4.5677e-41, 4.2796e-17, 4.5677e-41, 0.0000e+00, 0.0000e+00,
        0.0000e+00])

In [4]:
# checking the dimension of the scalar we created above
scalar.ndim

0

In [5]:
scalar2.ndim

1

In [6]:
# Now Checking the shape of Scalar we created above
scalar.shape

torch.Size([])

In [7]:
scalar2.shape

torch.Size([7])

In [8]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

 # Creating a Vecor!


 You can tell the number of dimensions a tensor in PyTorch has by the number of square brackets on the outside ([) and you only need to count one side.

In [9]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

Hmm, that's strange, vector contains two numbers but only has a single dimension.

I'll let you in on a trick.

You can tell the number of dimensions a tensor in PyTorch has by the number of square brackets on the outside ([) and you only need to count one side.

In [12]:
vector = torch.tensor([[7,8,9],[7,6,5]])
vector

tensor([[7, 8, 9],
        [7, 6, 5]])

In [13]:
vector.ndim

2

In [14]:
vector.shape

torch.Size([2, 3])

# Creating a 3-D Tensor

In [15]:
tensor_3d = torch.tensor([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
element = tensor_3d[2, 0, 1]
print(f"Below is the 3-D Tensor:\n {tensor_3d}")
print(f"Shape: {tensor_3d.shape}")
print(f"Dimentions: {tensor_3d.ndim}")
print(f"Total Elements: {tensor_3d.numel()}")
print(f"Element: {element}")


Below is the 3-D Tensor:
 tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]])
Shape: torch.Size([3, 1, 3])
Dimentions: 3
Total Elements: 9
Element: 8


In [16]:
element.item()

8

# Scalar V/s Vector V/s Matrix V/s Tensor


* Scalar --> 0-Dimention
* Vector --> 1-Dimention
* Matrix --> 2-Dimention
* Tensor --> 3-Dimention | n-Dimention


In [17]:
# Creating a Scalar
test_scalar = torch.tensor(7)
print(f"test_scalar: {test_scalar}")
print(f"shape: {test_scalar.shape}")
print(f"Dimentions: {test_scalar.ndim}")

test_scalar: 7
shape: torch.Size([])
Dimentions: 0


In [18]:
# Creating a Vector
test_vector = torch.tensor([1,2,3,4,5,6])
print(f"test_vector: {test_vector}")
print(f"shape: {test_vector.shape}")
print(f"Dimentions: {test_vector.ndim}")

test_vector: tensor([1, 2, 3, 4, 5, 6])
shape: torch.Size([6])
Dimentions: 1


In [19]:
# # Creating a Matrix
test_matrix = torch.tensor([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(f"test_matrix: {test_matrix}")
print(f"shape: {test_matrix.shape}")
print(f"Dimentions: {test_matrix.ndim}")

test_matrix: tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])
shape: torch.Size([2, 6])
Dimentions: 2


In [20]:
# Creating a Tensor 3D
test_tensor = torch.tensor([
    [
        [1,2,3],[4,5,6],[7,8,9]
    ],
    [
        [10,11,12],[13,14,15],[16,17,18]
    ],
    [
        [19,20,21],[22,23,24],[25,26,27]
    ]
  ])
print(f"test_tensor: {test_tensor}")
print(f"shape: {test_tensor.shape}")
print(f"Dimentions: {test_tensor.ndim}")


test_tensor: tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])
shape: torch.Size([3, 3, 3])
Dimentions: 3


### Random Tensors

In [21]:
# Creating a random tensor of shape(3,4)
random_tensor = torch.rand(size=(3,4))
print(f"Below is the Ranodm Tensor:\n {random_tensor}")
print(f"Size: {random_tensor.shape}")
print(f"Dimentions: {random_tensor.ndim}")

Below is the Ranodm Tensor:
 tensor([[0.3172, 0.3126, 0.7780, 0.6783],
        [0.7018, 0.9314, 0.1027, 0.6994],
        [0.6242, 0.9786, 0.7565, 0.7819]])
Size: torch.Size([3, 4])
Dimentions: 2


In [22]:
# Creating a Random Coloured Image Tensor

# Coloured Image Shape = Length x Width x Colour Channel
# (Colour Channel = 3 (Red, Green, Blue))
random_coloured_image_tensor = torch.rand(size=(244,244,3))
print(f"Coloured Image Tensor:\n {random_coloured_image_tensor}")
print(f"Size: {random_coloured_image_tensor.shape}")
print(f"Dimentions: {random_coloured_image_tensor.ndim}")
print(f"Total Elements: {random_coloured_image_tensor.numel()}")

Coloured Image Tensor:
 tensor([[[7.0458e-01, 4.8241e-01, 9.5324e-01],
         [7.9230e-01, 9.1760e-01, 6.7154e-01],
         [6.5910e-01, 6.7187e-01, 7.0235e-01],
         ...,
         [2.1675e-01, 8.8758e-03, 6.0803e-01],
         [2.7371e-01, 2.9522e-01, 4.3143e-01],
         [4.7186e-01, 4.5485e-01, 2.9061e-03]],

        [[5.8741e-01, 2.7139e-01, 5.7584e-01],
         [6.5654e-01, 6.4165e-01, 6.3624e-01],
         [3.4867e-01, 4.0367e-01, 9.2877e-01],
         ...,
         [2.2764e-01, 1.6957e-01, 5.2759e-01],
         [8.3906e-01, 9.8879e-01, 4.2900e-01],
         [9.1135e-01, 4.8601e-01, 1.3227e-01]],

        [[4.2180e-02, 9.3921e-01, 7.8013e-01],
         [8.1377e-01, 9.7049e-01, 8.6940e-01],
         [4.0417e-01, 4.3643e-01, 8.3114e-01],
         ...,
         [5.4193e-01, 8.4963e-01, 2.6461e-01],
         [2.3409e-01, 4.3874e-01, 7.0670e-01],
         [9.8870e-01, 6.9964e-01, 5.6413e-01]],

        ...,

        [[7.4082e-01, 1.4856e-01, 6.0178e-01],
         [3.6249e-01,

### Zeros and Ones Tensor


In [23]:
# Creating a zeros tensor of shape(3,4)
zeros_tensor = torch.zeros(size=(3,4))
print(f"Below is the Zeros Tensor:\n {zeros_tensor}")
print(f"Shape: {zeros_tensor.shape}")
print(f"Dimentions: {zeros_tensor.ndim}")
print(f"Total Elemnts: {zeros_tensor.numel()}")

Below is the Zeros Tensor:
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Shape: torch.Size([3, 4])
Dimentions: 2
Total Elemnts: 12


In [24]:
# Creating a Ones (1's) Tensor or shape(3,4)
ones_tensor = torch.ones(size=(3,4))
print(f"Below is the Ones Tensor:\n {ones_tensor}")
print(f"Shape: {ones_tensor.shape}")
print(f"Dimentions: {ones_tensor.ndim}")
print(f"Total Elements: {ones_tensor.numel()}")

Below is the Ones Tensor:
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Shape: torch.Size([3, 4])
Dimentions: 2
Total Elements: 12


### Creating a Tensor with arange()

In [25]:
# arange tensor --->   arange(start,end,jump)
one_to_ten = torch.arange(start=1, end=11, step=1)
print(f"Below is the 1-10 Tensor:\n {one_to_ten}")
print(f"Shape: {one_to_ten.shape}")
print(f"Dimentions: {one_to_ten.ndim}")
print(f"Total Elements: {one_to_ten.numel()}")

Below is the 1-10 Tensor:
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
Shape: torch.Size([10])
Dimentions: 1
Total Elements: 10


### Creating a Mask Using tensor_like(input=data)

In [26]:
data = one_to_ten
mask = torch.zeros_like(input=data)
print(f"Below is the 1-10 Tensor's Mask:\n {mask}")
print(f"Shape: {mask.shape}")
print(f"Dimentions: {mask.ndim}")
print(f"Total Elements: {mask.numel()}")

Below is the 1-10 Tensor's Mask:
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
Shape: torch.Size([10])
Dimentions: 1
Total Elements: 10


### Tensors Datatypes

**Note:** Tensors datatypes (dtype) is one of the 3 common errors you will run into with pytorch & DeepLearning

1. Tensor not Right Datatype
2. Tensor not Right Shape
3. Tensor not on the Right device  

In [27]:
float_32_tensor = torch.rand(size=(6,6,6), dtype=torch.float32, device=None, requires_grad=False)

float_32_tensor

tensor([[[8.4207e-01, 1.8184e-02, 1.7953e-02, 7.7321e-01, 8.1001e-01,
          4.5256e-01],
         [4.1781e-01, 3.7344e-01, 5.5854e-01, 1.2728e-01, 2.1377e-01,
          2.0325e-02],
         [2.6405e-05, 1.0305e-01, 3.0655e-01, 2.9025e-01, 4.9893e-01,
          1.4192e-01],
         [5.9298e-01, 1.6120e-01, 8.3402e-03, 3.0925e-01, 1.1980e-01,
          9.0254e-01],
         [3.2008e-01, 9.4406e-01, 2.7716e-01, 9.3024e-01, 3.8306e-01,
          8.9619e-01],
         [6.6407e-01, 5.4721e-01, 1.2425e-01, 5.0287e-01, 1.0181e-01,
          5.2099e-01]],

        [[7.2564e-01, 6.6207e-02, 6.4327e-02, 4.1870e-01, 8.0810e-01,
          4.7447e-01],
         [5.7955e-01, 5.5576e-01, 7.0249e-01, 6.4747e-01, 2.6304e-01,
          1.3803e-01],
         [6.6300e-01, 7.7370e-01, 8.8364e-01, 1.2338e-01, 1.6457e-01,
          5.9226e-01],
         [5.5290e-01, 6.5186e-01, 5.8187e-01, 5.4464e-01, 5.9608e-01,
          1.8744e-01],
         [1.5986e-01, 6.6840e-01, 2.7158e-01, 3.7032e-01, 8.9200e-01

In [28]:
float_16_tensor = torch.rand(size=(6,6,6), dtype=torch.float16, device="cpu", requires_grad=False)

float_16_tensor

tensor([[[0.5605, 0.5586, 0.2559, 0.6182, 0.1299, 0.7314],
         [0.3530, 0.8032, 0.9561, 0.8608, 0.0190, 0.2563],
         [0.9834, 0.4072, 0.2993, 0.2461, 0.2266, 0.1255],
         [0.2017, 0.4482, 0.6392, 0.3984, 0.2739, 0.6484],
         [0.7466, 0.8643, 0.0103, 0.1836, 0.8950, 0.7935],
         [0.0117, 0.0161, 0.7305, 0.8491, 0.5820, 0.4546]],

        [[0.0215, 0.9233, 0.6216, 0.9927, 0.7642, 0.6172],
         [0.4604, 0.3530, 0.7881, 0.9351, 0.3477, 0.8926],
         [0.0044, 0.5952, 0.6094, 0.7769, 0.1128, 0.3525],
         [0.4033, 0.7847, 0.2383, 0.2920, 0.2500, 0.0942],
         [0.5254, 0.3521, 0.4199, 0.2534, 0.1289, 0.6904],
         [0.9702, 0.9209, 0.7778, 0.3145, 0.6382, 0.9795]],

        [[0.2271, 0.6641, 0.1289, 0.0054, 0.3115, 0.4609],
         [0.1313, 0.6514, 0.5635, 0.9419, 0.7202, 0.9673],
         [0.2290, 0.0146, 0.9761, 0.7539, 0.2793, 0.8213],
         [0.1050, 0.7139, 0.0186, 0.3193, 0.0034, 0.6475],
         [0.0352, 0.1772, 0.7754, 0.5786, 0.0601, 0.

In [29]:
result = float_32_tensor * float_16_tensor

In [30]:
result

tensor([[[4.7202e-01, 1.0157e-02, 4.5935e-03, 4.7797e-01, 1.0521e-01,
          3.3102e-01],
         [1.4750e-01, 2.9996e-01, 5.3399e-01, 1.0957e-01, 4.0708e-03,
          5.2102e-03],
         [2.5966e-05, 4.1965e-02, 9.1755e-02, 7.1429e-02, 1.1304e-01,
          1.7809e-02],
         [1.1958e-01, 7.2257e-02, 5.3307e-03, 1.2322e-01, 3.2818e-02,
          5.8524e-01],
         [2.3897e-01, 8.1592e-01, 2.8420e-03, 1.7079e-01, 3.4284e-01,
          7.1109e-01],
         [7.7820e-03, 8.8173e-03, 9.0761e-02, 4.2700e-01, 5.9255e-02,
          2.3684e-01]],

        [[1.5590e-02, 6.1131e-02, 3.9985e-02, 4.1563e-01, 6.1752e-01,
          2.9284e-01],
         [2.6685e-01, 1.9620e-01, 5.5362e-01, 6.0542e-01, 9.1448e-02,
          1.2320e-01],
         [2.9136e-03, 4.6051e-01, 5.3847e-01, 9.5848e-02, 1.8563e-02,
          2.0879e-01],
         [2.2300e-01, 5.1149e-01, 1.3865e-01, 1.5903e-01, 1.4902e-01,
          1.7664e-02],
         [8.3987e-02, 2.3531e-01, 1.1404e-01, 9.3846e-02, 1.1498e-01

### Getting Information From the Tensors:

**Note:** Below are the 3 major errors that you will encounter while working in Pytorch & Deeplearning

* Tensore not Right Datatype - to get the Information about the Data type we use --> `tensor.dtype`
* Tensors not Right Shape - to get Information about the Shape we use --> `tensor.dtype`
* Tensors not Right Device - to get Information about the Device we use --> `tensor.device`


In [31]:
# Creating Some Tensor so that we can get the above information from it
some_tensor = torch.rand(size=(3,4), dtype=torch.float16, device="cpu")

print(f"Below is Some Tensor: \n{some_tensor}")
print(f"Shape of Tensor: {some_tensor.shape}")
print(f"Datatype of Tensor: {some_tensor.dtype}")
print(f"Device of Tensor: {some_tensor.device}")

Below is Some Tensor: 
tensor([[0.3184, 0.3066, 0.0552, 0.7256],
        [0.5869, 0.4297, 0.7349, 0.9785],
        [0.7661, 0.7993, 0.1587, 0.4507]], dtype=torch.float16)
Shape of Tensor: torch.Size([3, 4])
Datatype of Tensor: torch.float16
Device of Tensor: cpu


### Tensors Manipulation (Tensor Operations):

Tensor Operations Include:
- Addition
- Subtraction
- Multiplication (Element Wise)
- Division
- Matrix Multiplication

In [32]:
# creating a tensor
temp_tensor = torch.rand(size=(3,4), dtype=torch.float16, device="cpu")
temp_tensor

tensor([[0.2451, 0.0615, 0.9438, 0.3560],
        [0.5010, 0.5947, 0.2378, 0.0376],
        [0.7646, 0.0601, 0.1821, 0.0425]], dtype=torch.float16)

In [33]:
# Addition 2 to each element in the tensor
temp_tensor + 2

tensor([[2.2461, 2.0625, 2.9434, 2.3555],
        [2.5000, 2.5938, 2.2383, 2.0371],
        [2.7656, 2.0605, 2.1816, 2.0430]], dtype=torch.float16)

In [34]:
# Subtracting 5 from each elements in the tensor
temp_tensor - 5

tensor([[-4.7539, -4.9375, -4.0547, -4.6445],
        [-4.5000, -4.4062, -4.7617, -4.9609],
        [-4.2344, -4.9414, -4.8164, -4.9570]], dtype=torch.float16)

In [35]:
# Multipling 6 with each element in a Tensor
temp_tensor * 6

tensor([[1.4707, 0.3691, 5.6641, 2.1367],
        [3.0059, 3.5684, 1.4268, 0.2256],
        [4.5859, 0.3604, 1.0928, 0.2549]], dtype=torch.float16)

In [36]:
# Dividing each element of Tensor by 3
temp_tensor / 3

tensor([[0.0817, 0.0205, 0.3147, 0.1187],
        [0.1670, 0.1982, 0.0793, 0.0125],
        [0.2549, 0.0200, 0.0607, 0.0142]], dtype=torch.float16)

#Matrix Multiplication Must Match

## Rule
```
The Inner Dimentions must Match and the Outer Dimentions will Determine the size of the Resultant Matrix.

```

*  Matrix_A ----> Size(3,4)
*  Matrix_B ----> Size(4,7)


```

                4 x 4
             ___________
            |           |
      ( 3 x 4 )   x   ( 4 x 7 )
        |___________________|
               3 x 7

```
For Matrix Multiplication we can use @ symbol or we can use matmul()
* matrix_A @ matrix_B
* torch.matmul(matrix_A, matrix_B)

In [37]:
matrix_A = torch.rand(size=(3,4), dtype=torch.float32, device="cpu", requires_grad=False)
print(f"Below is the Matrix_A: \n{matrix_A}\n")
print(f"Size = {matrix_A.shape}")
print(f"Dimentions = {matrix_A.ndim}")
print(f"Total Elements = {matrix_A.numel()}")

Below is the Matrix_A: 
tensor([[0.2732, 0.8485, 0.1286, 0.7896],
        [0.7696, 0.7201, 0.2866, 0.9491],
        [0.0732, 0.8226, 0.2730, 0.0542]])

Size = torch.Size([3, 4])
Dimentions = 2
Total Elements = 12


In [38]:
matrix_B = torch.rand(size=(4,7), dtype=torch.float32, device="cpu", requires_grad=False)
print(f"Below is the Matrix_A: \n{matrix_B}\n")
print(f"Size = {matrix_B.shape}")
print(f"Dimentions = {matrix_B.ndim}")
print(f"Total Elements = {matrix_B.numel()}")

Below is the Matrix_A: 
tensor([[0.8178, 0.3584, 0.5807, 0.7007, 0.4646, 0.1778, 0.9799],
        [0.1173, 0.3795, 0.5738, 0.4488, 0.9054, 0.9129, 0.4708],
        [0.2983, 0.3026, 0.7972, 0.7964, 0.5145, 0.9852, 0.0860],
        [0.7387, 0.5545, 0.4853, 0.1966, 0.2841, 0.1268, 0.1854]])

Size = torch.Size([4, 7])
Dimentions = 2
Total Elements = 28


In [39]:
result = torch.matmul(matrix_A, matrix_B)
print(f"Below is the Resultant Matrix: \n{result}\n")
print(f"Size = {result.shape}")
print(f"Dimentions = {result.ndim}")
print(f"Total Elements = {result.numel()}")

Below is the Resultant Matrix: 
tensor([[0.9445, 0.8966, 1.1312, 0.8299, 1.1857, 1.0500, 0.8246],
        [1.5004, 1.1621, 1.5492, 1.2774, 1.4267, 1.1970, 1.2938],
        [0.2778, 0.4510, 0.7584, 0.6485, 0.9346, 1.0398, 0.4925]])

Size = torch.Size([3, 7])
Dimentions = 2
Total Elements = 21


# Tensor Aggregation

Finding the min(), max(), mean(), sum() etc

In [40]:
x = torch.arange(0,100,10)
print(f"Below is the Tensor: \n{x}\n")
print(f"Size = {x.shape}")
print(f"Dimentions = {x.ndim}")
print(f"Total Elements = {x.numel()}")

Below is the Tensor: 
tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

Size = torch.Size([10])
Dimentions = 1
Total Elements = 10


In [41]:
# Finding the Max Element
print(f"Max Element: {x.max()}")
print(f"Max Element: {torch.max(x)}" )

Max Element: 90
Max Element: 90


In [42]:
# Finding the Min Element
print(f"Min Element: {x.min()}")
print(f"Min Element: {torch.min(x)}")

Min Element: 0
Min Element: 0


In [43]:
# Finding the Mean Value | Note: The torch.mean() function require a tensor of float32 datatype to operate
print(f"Mean Value: {x.type(torch.float32).mean()}")
print(f"Mean Value: {torch.mean(x.type(torch.float32))}")

Mean Value: 45.0
Mean Value: 45.0


In [44]:
# Finding the Sum
print(f"Sum: {x.sum()}")
print(f"Sum: {torch.sum(x)}")

Sum: 450
Sum: 450


# Finding the Positional Max and Min

* Index with Min Value --> agrmin()
* Index with Max Value --> argmax()


In [45]:
# Finding the Index Position with the Maximum Value
print(f"Max Index: {x.argmax()}")
print(f"Value on Max Index: {x[x.argmax()]}")

Max Index: 9
Value on Max Index: 90


In [46]:
# Finding the Index Position with the Minimum Value
print(f"Min Index: {x.argmin()}")
print(f"Value on Min Index: {x[x.argmin()]}")

Min Index: 0
Value on Min Index: 0


# Reshaping, Stacking, Squeezing and Un-Squeezing Tensors

* Reshaping - Reshapes an Input Tensor to a defined Shape
* View - Returns a View of an input Tensor of certain shape but keep the same memory as the original Tensor
* Stacking - Combine Multiple Tensors on Top of each other Vertically (vstack) or Horizontally (hstack)
* Squeeze - Removes all 1 Dimentions from a given Tensor
* Un-Squeeze - Add 1 Dimention to the target Tensor
* Permute - Returns a View of the Input with Dimention Permuted (swapped) in a Certain way

In [47]:
import torch

x = torch.randint(low=0, high=10, size=(1,12), dtype=torch.float32)
print(f"Below is the Tensor: \n{x}\n")
print(f"Size = {x.shape}")
print(f"Dimentions = {x.ndim}")
print(f"Total Elements = {x.numel()}")

Below is the Tensor: 
tensor([[3., 9., 3., 7., 1., 0., 6., 6., 6., 2., 4., 6.]])

Size = torch.Size([1, 12])
Dimentions = 2
Total Elements = 12


In [48]:
# Reshaping the Tensor x
x_reshaped = x.reshape(3,4)
print(f"Below is the Reshaped Tensor: \n{x_reshaped}\n")
print(f"Size = {x_reshaped.shape}")
print(f"Dimentions = {x_reshaped.ndim}")
print(f"Total Elements = {x_reshaped.numel()}")

Below is the Reshaped Tensor: 
tensor([[3., 9., 3., 7.],
        [1., 0., 6., 6.],
        [6., 2., 4., 6.]])

Size = torch.Size([3, 4])
Dimentions = 2
Total Elements = 12


In [49]:
# Creating a View
z = x.view(1,12)
z

# Z is a view created as per x Because original Tensors share memory with views
# So, if they are sharing memory this means changing z would reflect the changes in z

# Changing z means changing x
print(x)
z[:, 3] = 25.6
z,x


tensor([[3., 9., 3., 7., 1., 0., 6., 6., 6., 2., 4., 6.]])


(tensor([[ 3.0000,  9.0000,  3.0000, 25.6000,  1.0000,  0.0000,  6.0000,  6.0000,
           6.0000,  2.0000,  4.0000,  6.0000]]),
 tensor([[ 3.0000,  9.0000,  3.0000, 25.6000,  1.0000,  0.0000,  6.0000,  6.0000,
           6.0000,  2.0000,  4.0000,  6.0000]]))

In [50]:
# Stacking
x_stack = torch.stack([x,x,x,x,x,x,x], dim=0)
x_stack

tensor([[[ 3.0000,  9.0000,  3.0000, 25.6000,  1.0000,  0.0000,  6.0000,
           6.0000,  6.0000,  2.0000,  4.0000,  6.0000]],

        [[ 3.0000,  9.0000,  3.0000, 25.6000,  1.0000,  0.0000,  6.0000,
           6.0000,  6.0000,  2.0000,  4.0000,  6.0000]],

        [[ 3.0000,  9.0000,  3.0000, 25.6000,  1.0000,  0.0000,  6.0000,
           6.0000,  6.0000,  2.0000,  4.0000,  6.0000]],

        [[ 3.0000,  9.0000,  3.0000, 25.6000,  1.0000,  0.0000,  6.0000,
           6.0000,  6.0000,  2.0000,  4.0000,  6.0000]],

        [[ 3.0000,  9.0000,  3.0000, 25.6000,  1.0000,  0.0000,  6.0000,
           6.0000,  6.0000,  2.0000,  4.0000,  6.0000]],

        [[ 3.0000,  9.0000,  3.0000, 25.6000,  1.0000,  0.0000,  6.0000,
           6.0000,  6.0000,  2.0000,  4.0000,  6.0000]],

        [[ 3.0000,  9.0000,  3.0000, 25.6000,  1.0000,  0.0000,  6.0000,
           6.0000,  6.0000,  2.0000,  4.0000,  6.0000]]])

In [51]:
# torch.squeeze() --> Removes all the single dimentions for a Targeted Tensor

# Creating a Tensor
tensor = torch.arange(1,10,1)
# Reshaping the Tensor
reshaped_tensor = tensor.reshape(1,9)



print(f"Tensor Before Squeezing: \n{reshaped_tensor}\n")
print(f"Size = {reshaped_tensor.shape}")
print(f"Dimentions = {reshaped_tensor.ndim}")
print(f"Total Elements = {reshaped_tensor.numel()}")

print(f"\n________________________________________________\n")
squzeed_tensor = reshaped_tensor.squeeze()
print(f"Tensor After Squeezing: \n{squzeed_tensor}\n")
print(f"Size = {squzeed_tensor.shape}")
print(f"Dimentions = {squzeed_tensor.ndim}")
print(f"Total Elements = {squzeed_tensor.numel()}")

Tensor Before Squeezing: 
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

Size = torch.Size([1, 9])
Dimentions = 2
Total Elements = 9

________________________________________________

Tensor After Squeezing: 
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

Size = torch.Size([9])
Dimentions = 1
Total Elements = 9


In [52]:
# torch.unsqueeze() --> Adds 1 in the shape of the tensor at a specific Dimention


print(f"Tensor Before Un-Squeezing: \n{squzeed_tensor}\n")
print(f"Size = {squzeed_tensor.shape}")
print(f"Dimentions = {squzeed_tensor.ndim}")
print(f"Total Elements = {squzeed_tensor.numel()}")

print(f"\n________________________________________________\n")
unsquzeed_tensor = squzeed_tensor.unsqueeze(dim=0)
print(f"Tensor After Squeezing: \n{unsquzeed_tensor}\n")
print(f"Size = {unsquzeed_tensor.shape}")
print(f"Dimentions = {unsquzeed_tensor.ndim}")
print(f"Total Elements = {unsquzeed_tensor.numel()}")

Tensor Before Un-Squeezing: 
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

Size = torch.Size([9])
Dimentions = 1
Total Elements = 9

________________________________________________

Tensor After Squeezing: 
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

Size = torch.Size([1, 9])
Dimentions = 2
Total Elements = 9


In [53]:
# torch.permute --> Rearrange the Dimentions of a Targeted Tensor in a Specified Order

original_image = torch.rand(size=(244,244,3), dtype=torch.float32)
print(f"            Size of the Original Image")
print(f"Size = {original_image.shape}\n") # [height, width, color_channel]
print(f"\n________________________________________________\n")
permuted_image = original_image.permute(2,0,1) # shift axis 0->1, 1->2, 2->0
print(f"            Size of the Permuted Image")
print(f"Size = {original_image.shape}\n") # [color_channel, height, width]

original_image[0,0,0] = 23.00
print(original_image)
print("\n_______\n")
print(permuted_image)

            Size of the Original Image
Size = torch.Size([244, 244, 3])


________________________________________________

            Size of the Permuted Image
Size = torch.Size([244, 244, 3])

tensor([[[2.3000e+01, 8.1951e-01, 2.5671e-01],
         [1.8920e-01, 7.0211e-01, 7.2338e-01],
         [1.8867e-01, 1.0342e-02, 4.1315e-01],
         ...,
         [8.9394e-01, 1.4147e-01, 2.6697e-01],
         [5.5021e-01, 2.0882e-01, 6.3864e-01],
         [8.4481e-01, 8.8068e-01, 4.9300e-01]],

        [[4.7530e-01, 1.0552e-01, 6.3946e-01],
         [8.9511e-01, 3.6351e-01, 2.7980e-01],
         [3.6070e-01, 3.6260e-01, 6.7559e-01],
         ...,
         [6.5217e-02, 5.5197e-01, 4.0203e-01],
         [1.4405e-01, 6.9930e-01, 3.9730e-01],
         [3.7161e-01, 4.0598e-01, 6.9938e-01]],

        [[8.4362e-01, 5.9552e-01, 2.4761e-01],
         [6.4602e-01, 1.2544e-01, 6.4525e-01],
         [4.8799e-01, 8.8634e-01, 5.4367e-01],
         ...,
         [8.4454e-01, 8.4330e-01, 7.2388e-01],
     

#PyTorch Tensors and Numpy
Numpy is a popular Scientific Python Numerial Computing Laibrary
And because of this PyTorch has functionality to Interact with this

* Data in Numpy, want it in PyTorch --> `torch.from_numpy(ndarray)`
* PyTorch --> Numpy ---> `torch.Tensor.Numpy()`

In [54]:
# Numpy Array to Tensors
import torch
import numpy as np

array = np.arange(1,12,2)

# Now we need to convert the Numpy Array to PyTorch Tensor
tensor = torch.from_numpy(array)

array, tensor

(array([ 1,  3,  5,  7,  9, 11]), tensor([ 1,  3,  5,  7,  9, 11]))

In [55]:
# Verifing the data type of the Numpy Array and PyTorch Tensor
array.dtype, tensor.dtype

(dtype('int64'), torch.int64)

In [56]:
# Changing the Numpy Array to check whether the changes reflect in the PyTorch Tensor
array = array + 1
array, tensor

(array([ 2,  4,  6,  8, 10, 12]), tensor([ 1,  3,  5,  7,  9, 11]))

In [57]:
# Converting the PyTorch Tensor to Numpy Array
pytorch_tensor = torch.rand(size=(3,4))
numpy_array = pytorch_tensor.numpy()
pytorch_tensor, numpy_array

(tensor([[0.4125, 0.2345, 0.0047, 0.9276],
         [0.7943, 0.9087, 0.6646, 0.9137],
         [0.2114, 0.1237, 0.4264, 0.9487]]),
 array([[0.41254884, 0.2344963 , 0.00469947, 0.92760205],
        [0.7943312 , 0.90866923, 0.66458666, 0.91366154],
        [0.21138644, 0.12365049, 0.42644513, 0.94868547]], dtype=float32))

# Reproducbility (Trying to take Random out of Random)
In Short How Neural Network Learns:

`Start of Random Numbers --> Tensor Operations --> Update Random Number to Try and Make them of Data ---> again --> again --> again ... `

* To Reduce the concept of Randomness in Neural Network and PyTorch comes with the concept of Random Seed

Essentially what the Random Seed does is to "flavour" the concept of Randomness

In [58]:
tensor_A = torch.rand(size=(3,4), dtype=torch.float32)
tensor_B = torch.rand(size=(3,4), dtype=torch.float32)
print(tensor_A)
print(tensor_B)
print(tensor_A == tensor_B)

tensor([[0.4722, 0.6639, 0.9508, 0.7700],
        [0.9709, 0.7469, 0.8876, 0.6828],
        [0.5149, 0.2360, 0.1307, 0.6405]])
tensor([[0.9506, 0.9164, 0.2682, 0.9502],
        [0.3869, 0.2942, 0.2888, 0.4943],
        [0.5813, 0.4526, 0.9332, 0.0604]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [59]:
# As we have wittnised the Values in both the Tensors are not the same
# Now lets give it a try using RANDOM SEED

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
tensor_C = torch.rand(size=(3,4), dtype=torch.float32)

torch.manual_seed(RANDOM_SEED)
tensor_D = torch.rand(size=(3,4), dtype=torch.float32)

print(tensor_C)
print(tensor_D)
print(tensor_C == tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Nvidia System Management Interface

In [60]:
!nvidia-smi


Mon Jun  8 08:09:51 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   37C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [61]:
# Check for GPU Access with Python\
import torch
torch.cuda.is_available()

True

##Setting up Device Agnostic Code

In [63]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [64]:
# Check the Number of Avaliable/Assigned Devices
torch.cuda.device_count()

1

## Putting Tensors (and Models) on GPU
The reason why we want our Tensor/Model on GPU because the GPU results in Fast Computation

In [65]:
# Creating a Tensor Default on CPU
tensor = torch.tensor([2,4,6,8])

# tensor not on CPU
tensor, tensor.device

(tensor([2, 4, 6, 8]), device(type='cpu'))

In [66]:
# Move Tensor to GPU if avaliable
tensor_on_gpu = tensor.to(device)
tensor_on_gpu.device

device(type='cuda', index=0)

## Moving Tensor Back to the CPU
while if a tensor is on GPU, you can't transform it to Numpy


In [67]:
# Moving Tensor Back to GPU, can't  transform it to Numpy()
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [71]:
# Switching from GPU to CPU, for Numpy Transformation
tensor_on_cpu = tensor_on_gpu.cpu()
tensor_on_cpu.numpy(), tensor_on_cpu.device

(array([2, 4, 6, 8]), device(type='cpu'))